SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";
CREATE TABLE `devices` (`id` int(10) UNSIGNED NOT NULL, `vendor_id` varchar(6) COLLATE utf8_unicode_ci NOT NULL, `product_id` varchar(6) COLLATE utf8_unicode_ci DEFAULT NULL, `name` varchar(128) COLLATE utf8_unicode_ci NOT NULL, `flash_program` int(11) NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
INSERT INTO `devices` (`id`, `vendor_id`, `product_id`, `name`, `flash_program`) VALUES (1, '0x0d28', '0x0204', 'Phytec phyWAVE-KW22', 0);
INSERT INTO `devices` (`id`, `vendor_id`, `product_id`, `name`, `flash_program`) VALUES (2, '0x2047', NULL, 'MSP430 (family)', 0);
INSERT INTO `devices` (`id`, `vendor_id`, `product_id`, `name`, `flash_program`) VALUES (3, '0x03eb', NULL, 'ATmega (family)', 0);
INSERT INTO `devices` (`id`, `vendor_id`, `product_id`, `name`, `flash_program`) VALUES (4, '0x0483', NULL, 'MIPS (family)', 0);
INSERT INTO `devices` (`id`, `vendor_id`, `product_id`, `name`, `flash_program`) VALUES (5, '0x0483', NULL, 'Nucleo family', 0);
INSERT INTO `devices` (`id`, `vendor_id`, `product_id`, `name`, `flash_program`) VALUES (6, '0x0483', '0x3748', 'Airfy Beacon', 0);
INSERT INTO `devices` (`id`, `vendor_id`, `product_id`, `name`, `flash_program`) VALUES (7, '0x2a03', '0x003d', 'Arduino Due (usb2serial)', 0);
INSERT INTO `devices` (`id`, `vendor_id`, `product_id`, `name`, `flash_program`) VALUES (8, '0x2a03', '0x003e', 'Arduino Due', 0);
INSERT INTO `devices` (`id`, `vendor_id`, `product_id`, `name`, `flash_program`) VALUES (9, '0x03eb', '0x6121', 'Arduino Zero', 0);
INSERT INTO `devices` (`id`, `vendor_id`, `product_id`, `name`, `flash_program`) VALUES (10, '0x0403', NULL, 'CC2650STK', 0);
INSERT INTO `devices` (`id`, `vendor_id`, `product_id`, `name`, `flash_program`) VALUES (11, '0x0403', '0xa6d1', 'CC2538DK', 0);
INSERT INTO `devices` (`id`, `vendor_id`, `product_id`, `name`, `flash_program`) VALUES (12, '0x0483', NULL, 'LimiFrog-v1', 0);
INSERT INTO `devices` (`id`, `vendor_id`, `product_id`, `name`, `flash_program`) VALUES (13, '0x0d28', '0x0204', 'mbed_lpc1768', 0);
INSERT INTO `devices` (`id`, `vendor_id`, `product_id`, `name`, `flash_program`) VALUES (14, '0x1915', NULL, 'micro:bit', 0);
INSERT INTO `devices` (`id`, `vendor_id`, `product_id`, `name`, `flash_program`) VALUES (15, '0x0483', NULL, 'MSB-IoT', 0);
INSERT INTO `devices` (`id`, `vendor_id`, `product_id`, `name`, `flash_program`) VALUES (16, '0x0483', '0x374b', 'Nucleo-F334', 0);
INSERT INTO `devices` (`id`, `vendor_id`, `product_id`, `name`, `flash_program`) VALUES (17, '0x0483', '0x374b', 'Nucleo-F103', 0);
INSERT INTO `devices` (`id`, `vendor_id`, `product_id`, `name`, `flash_program`) VALUES (18, '0x0483', NULL, 'Nucleo-F091', 0);
INSERT INTO `devices` (`id`, `vendor_id`, `product_id`, `name`, `flash_program`) VALUES (19, '0x0483', NULL, 'Nucleo-F072', 0);
INSERT INTO `devices` (`id`, `vendor_id`, `product_id`, `name`, `flash_program`) VALUES (20, '0x0483', NULL, 'Nucleo-F070', 0);
INSERT INTO `devices` (`id`, `vendor_id`, `product_id`, `name`, `flash_program`) VALUES (21, '0x0483', NULL, 'Nucleo-F030', 0);
INSERT INTO `devices` (`id`, `vendor_id`, `product_id`, `name`, `flash_program`) VALUES (22, '0x0483', NULL, 'Nucleo32-F303', 0);
INSERT INTO `devices` (`id`, `vendor_id`, `product_id`, `name`, `flash_program`) VALUES (23, '0x0483', NULL, 'Nucleo32-F042', 0);
INSERT INTO `devices` (`id`, `vendor_id`, `product_id`, `name`, `flash_program`) VALUES (24, '0x0483', NULL, 'Nucleo32-F031', 0);
INSERT INTO `devices` (`id`, `vendor_id`, `product_id`, `name`, `flash_program`) VALUES (25, '0x0483', NULL, 'NZ32-SC151', 0);
INSERT INTO `devices` (`id`, `vendor_id`, `product_id`, `name`, `flash_program`) VALUES (26, '0x0451', NULL, 'OpenMote', 0);
INSERT INTO `devices` (`id`, `vendor_id`, `product_id`, `name`, `flash_program`) VALUES (27, '0x1915', NULL, 'PCA1000x (nRF51822 Development Kit)', 0);
INSERT INTO `devices` (`id`, `vendor_id`, `product_id`, `name`, `flash_program`) VALUES (28, '0x1915', NULL, 'RFduino', 0);
INSERT INTO `devices` (`id`, `vendor_id`, `product_id`, `name`, `flash_program`) VALUES (29, '0x03eb', NULL, 'SAMD21-xpro', 0);
INSERT INTO `devices` (`id`, `vendor_id`, `product_id`, `name`, `flash_program`) VALUES (30, '0x0d28', NULL, 'Seeeduino Arch-Pro', 0);
INSERT INTO `devices` (`id`, `vendor_id`, `product_id`, `name`, `flash_program`) VALUES (31, '0x03eb', NULL, 'SODAQ Autonomo', 0);
INSERT INTO `devices` (`id`, `vendor_id`, `product_id`, `name`, `flash_program`) VALUES (32, '0x1d50', '0x607f', 'Spark Core', 0);
INSERT INTO `devices` (`id`, `vendor_id`, `product_id`, `name`, `flash_program`) VALUES (33, '0x03eb', NULL, 'SparkFun SAMD21 Mini', 0);
INSERT INTO `devices` (`id`, `vendor_id`, `product_id`, `name`, `flash_program`) VALUES (34, '0x0483', NULL, 'STM32F0discovery', 0);
INSERT INTO `devices` (`id`, `vendor_id`, `product_id`, `name`, `flash_program`) VALUES (35, '0x0483', NULL, 'STM32F3discovery', 0);
INSERT INTO `devices` (`id`, `vendor_id`, `product_id`, `name`, `flash_program`) VALUES (36, '0x0483', NULL, 'STM32F4discovery', 0);
INSERT INTO `devices` (`id`, `vendor_id`, `product_id`, `name`, `flash_program`) VALUES (37, '0x1915', NULL, 'yunjia-nrf51822', 0);
INSERT INTO `devices` (`id`, `vendor_id`, `product_id`, `name`, `flash_program`) VALUES (38, '0x03eb', '0x0042', 'Arduino Mega2560', 0);
INSERT INTO `devices` (`id`, `vendor_id`, `product_id`, `name`, `flash_program`) VALUES (39, '0x03eb', '0x0043', 'Arduino Uno', 0);
INSERT INTO `devices` (`id`, `vendor_id`, `product_id`, `name`, `flash_program`) VALUES (40, '0x03eb', NULL, 'Arduino Duemilanove', 0);
INSERT INTO `devices` (`id`, `vendor_id`, `product_id`, `name`, `flash_program`) VALUES (41, '0x2047', NULL, 'MSB-430H', 0);
INSERT INTO `devices` (`id`, `vendor_id`, `product_id`, `name`, `flash_program`) VALUES (42, '0x2047', NULL, 'TelosB', 0);
INSERT INTO `devices` (`id`, `vendor_id`, `product_id`, `name`, `flash_program`) VALUES (43, '0x2047', NULL, 'WSN430', 0);
INSERT INTO `devices` (`id`, `vendor_id`, `product_id`, `name`, `flash_program`) VALUES (44, '0x2047', NULL, 'eZ430-Chronos', 0);
INSERT INTO `devices` (`id`, `vendor_id`, `product_id`, `name`, `flash_program`) VALUES (45, '0x04d8', '0x00e0', 'PIC32-WiFire', 0);
INSERT INTO `devices` (`id`, `vendor_id`, `product_id`, `name`, `flash_program`) VALUES (46, '0x042b', NULL, 'Intel Galileo', 0);
INSERT INTO `devices` (`id`, `vendor_id`, `product_id`, `name`, `flash_program`) VALUES (47, '0x8086', NULL, 'Intel Galileo', 0);
INSERT INTO `devices` (`id`, `vendor_id`, `product_id`, `name`, `flash_program`) VALUES (48, '0x8087', NULL, 'Intel Galileo', 0);
INSERT INTO `devices` (`id`, `vendor_id`, `product_id`, `name`, `flash_program`) VALUES (49, '0x0000', NULL, 'HikoB Fox', 0);
INSERT INTO `devices` (`id`, `vendor_id`, `product_id`, `name`, `flash_program`) VALUES (50, '0x0000', NULL, 'IoT LAB M3', 0);
INSERT INTO `devices` (`id`, `vendor_id`, `product_id`, `name`, `flash_program`) VALUES (51, '0x0000', NULL, 'MSBA2', 0);
INSERT INTO `devices` (`id`, `vendor_id`, `product_id`, `name`, `flash_program`) VALUES (52, '0x0000', NULL, 'Mulle', 0);
INSERT INTO `devices` (`id`, `vendor_id`, `product_id`, `name`, `flash_program`) VALUES (53, '0x0000', NULL, 'UDOO', 0);
INSERT INTO `devices` (`id`, `vendor_id`, `product_id`, `name`, `flash_program`) VALUES (54, '0x0000', NULL, 'Zolertia remote', 0);
INSERT INTO `devices` (`id`, `vendor_id`, `product_id`, `name`, `flash_program`) VALUES (55, '0x0000', NULL, 'Zolertia Z1', 0);
ALTER TABLE `devices` ADD PRIMARY KEY (`id`);
ALTER TABLE `devices` MODIFY `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=56;